In [2]:
import pandas as pd
import numpy as np
from itertools import product
import utils

/Users/amelie/Library/CloudStorage/OneDrive-epfl.ch/04_Operations/project/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

# Cleaning the data and merging with coordinates

In [ ]:
# Merging the two files
data1 = pd.read_excel('Clientes Colombia Marzo 2.xlsx')
data2 = pd.read_excel('Clientes Colombia Marzo 3 (1).xlsx')

df = pd.concat([data1, data2], ignore_index=True)
# I removed the intermediary step where we turn this into a csv to remove clutter
# df.to_csv('columbia_full.csv', index=False)

# Opening demand file
# df = pd.read_csv('columbia_full.csv')
df.rename(columns={'FechaPlanInicioTransporte':'date', 'RegionalDistribucion': 'region','IDCentro':'Center_ID','CodigoCliente':'Client_ID'}, inplace=True)
df.drop(columns = ['Plan_Vol','plan_boxes','DocumentoTransporte','Ordered_vol'], inplace=True)

# Merging with the coordinates of the centers
coordinates_centers = pd.read_csv('Coordenadas CDs.csv', encoding='latin1')
coordinates_centers.drop(columns=['Nombre','Direccin','CD.1'], inplace=True)
coordinates_centers.rename(columns={'CD':'CD','Latitud':'Latitude_CD','Longitud':'Longitude_CD'}, inplace=True)

df = df.merge(coordinates_centers, how='inner', left_on='Center_ID', right_on='CD')

df.drop(columns=['CD'], inplace=True)
# Merging with the coordinates of the clients
coordinates_clients = pd.read_csv('Coordenadas Clientes.csv', encoding='latin1')
coordinates_clients = coordinates_clients[['CD CODE','CLIENT #','LATITUDE','LENGTH']]
coordinates_clients.rename(columns={'CD CODE':'Center_ID','CLIENT #':'Client_ID','LATITUDE':'Latitude_Client','LENGTH':'Longitude_Client'}, inplace=True)
coordinates_clients

df = df.merge(coordinates_clients, how='inner', left_on=['Client_ID','Center_ID'], right_on=['Client_ID','Center_ID'])

# Translating boxes into hL
df['ordered_volume'] = df['ordered_boxes'] * 0.0756

# In case needed to have date in datetime format
df['date'] = pd.to_datetime(df['date'])

# Saving the final dataframe
df.to_csv('columbia_full_coordinates.csv', index=False)

/var/folders/t8/crqx384x59sbfjcs2flq1d380000gn/T/ipykernel_37179/1531093525.py:15: DtypeWarning: Columns (8,9,11,12,14) have mixed types. Specify dtype option on import or set low_memory=False.
  coordinates_clients = pd.read_csv('Coordenadas Clientes.csv', encoding='latin1')

In [7]:
df = pd.read_csv('columbia_full_coordinates.csv')
df

,date,region,Center_ID,Client_ID,ordered_boxes,Latitude_CD,Longitude_CD,Latitude_Client,Longitude_Client,ordered_volume
0,2025-03-18,Sur,AV46,11645498,50.00,3.535408,-76.492858,3.449400,-76.522300,3.780000
1,2025-03-01,Centro,AV47,12307950,12.02,4.541264,-74.251706,4.562510,-74.236074,0.908712
2,2025-03-06,Centro,AV26,13212774,2.00,4.596453,-74.148856,4.563009,-74.104803,0.151200
3,2025-03-31,Norte,AV39,12946586,102.25,8.729500,-75.847328,8.953745,-75.838556,7.730100
4,2025-03-20,Sur,AV18,13682698,6.00,2.915592,-75.285719,2.924496,-75.259561,0.453600
...,...,...,...,...,...,...,...,...,...,...
406924,2025-03-20,Centro,AV47,10640224,8.50,4.541264,-74.251706,4.615580,-74.351343,0.642600
406925,2025-03-15,Andes,AV05,14260184,5.75,6.168617,-75.618514,6.171558,-75.610056,0.434700
406926,2025-03-12,Centro,AV06,14208244,32.00,4.946467,-73.941175,4.908358,-73.942483,2.419200
406927,2025-03-18,Sur,AV24,12610824,19.52,5.280189,-72.427817,5.181973,-72.572259,1.475712
406928,2025-03-29,Sur,AV15,13165100,52.75,1.154189,-77.305711,1.130100,-77.548000,3.987900

In [13]:
# Group by Client_ID and calculate the total ordered volume per client
client_volumes = df[df['region'] == 'Centro'].groupby('Client_ID')['ordered_volume'].sum()

# Sort clients by ordered volume in descending order
client_volumes = client_volumes.sort_values(ascending=False)

# Calculate the cumulative sum of ordered volumes and the total ordered volume
cumulative_volume = client_volumes.cumsum()
total_volume = client_volumes.sum()

# Select clients that together represent 50% of the total ordered volume
clients_50_percent = client_volumes[cumulative_volume <= 0.5 * total_volume].index

# Filter the dataframe for these customers
filtered_df = df[df['Client_ID'].isin(clients_50_percent)]

filtered_df
# Save the filtered dataframe to a CSV file
filtered_df.to_csv('clients_50_percent.csv', index=False)

In [18]:
df = pd.read_csv('clients_50_percent.csv')
print(pd.unique(df['region']))
df.head()

['Centro']

,date,region,Center_ID,Client_ID,ordered_boxes,Latitude_CD,Longitude_CD,Latitude_Client,Longitude_Client,ordered_volume
0,2025-03-30,Centro,AV06,10794836,500.0,4.946467,-73.941175,4.617067,-74.090837,37.800
1,2025-03-14,Centro,AV26,10753140,125.0,4.596453,-74.148856,4.370634,-74.187603,9.450
2,2025-03-26,Centro,AV06,13969047,750.0,4.946467,-73.941175,4.642541,-74.077412,56.700
3,2025-03-14,Centro,AV06,12468175,700.0,4.946467,-73.941175,4.606485,-74.085070,52.920
4,2025-03-11,Centro,AV47,12408426,560.0,4.541264,-74.251706,4.540471,-74.255110,42.336

In [ ]:
# This is to decompose the problem as much as possible
center = 'AV16'
date = '2025-03-29'

subproblem_df = df[(df['Center_ID'] == center) & (df['date'] == date)].copy()
subproblem_df.reset_index(drop=True, inplace=True)
subproblem_df.head()
subproblem_df.to_csv('subproblem.csv', index=False)

# This is useful to pick out a value at random if needed:
# df['date'].sample(1).iloc[0]

In [47]:
depot = (subproblem_df['Latitude_CD'].iloc[0], subproblem_df['Longitude_CD'].iloc[0])
clients = (subproblem_df[['Latitude_Client', 'Longitude_Client']].values)

unique_clients = np.unique(clients, axis=0)
subset_locations = np.vstack([depot, unique_clients[:9]])
all_locations = np.vstack([depot, unique_clients])

In [58]:
# First attempt with only 3 clients

def distance_matrix(depot, clients, sample_size = 3):
    """
    Function to calculate the distance and time matrix between the depot and clients
    depot: tuple / list with the coordinates of the depot
    clients: array with the coordinates of the clients as tuples / lists
    sample_size: number of clients to sample from the list of clients
    """
    clients_sample = clients[:sample_size]
    locations = np.vstack([depot, clients_sample])

    distance_matrix = np.zeros((len(locations), len(locations)))
    time_matrix = np.zeros((len(subset_locations), len(subset_locations)))

    for i in range(len(locations)):
        for j in range(len(locations)):
            dist, time = utils.get_distance(locations[i], locations[j])
            distance_matrix[i, j] = dist
            time_matrix[i, j] = time
    return distance_matrix, time_matrix

dist_mtx1, time_mtx1 = utils.distance_time_matrix(depot = depot, clients = unique_clients, sample_size = 3)

print(dist_mtx1)

AttributeError: module 'utils' has no attribute 'distance_time_matrix'

In [4]:
subproblem_df = pd.read_csv('subproblem.csv')
depot = (subproblem_df['Latitude_CD'].iloc[0], subproblem_df['Longitude_CD'].iloc[0])
print(depot)

clients = (subproblem_df[['Latitude_Client', 'Longitude_Client']].values)
clients = np.unique(clients, axis=0)

dist_matrix, time_matrix = utils.distance_time_matrix(depot, clients, sample_size = len(clients))

dist_matrix.to_csv('distance_matrix_subproblem.csv', index=False)
time_matrix.to_csv('time_matrix_subproblem.csv', index=False)

(np.float64(4.802644), np.float64(-75.832822))

KeyboardInterrupt:

In [ ]:
regions = pd.unique(df['RegionalDistribucion'])
n_centres = len(pd.unique(df['IDCentro']))
print(f"Regions: {regions}, Number of centres: {n_centres}")

Regions: ['Sur' 'Centro' 'Norte' 'Andes'], Number of centres: 64

In [3]:
df.groupby('CodigoCliente').size().sort_values(ascending=False) # Number of orders

CodigoCliente
13937684    231
10359686    112
11430868     97
10151328     81
10316879     69
           ...
12596356      1
12596294      1
12596293      1
12596275      1
14323128      1
Length: 217343, dtype: int64

In [4]:
df.groupby('CodigoCliente')['ordered_boxes'].mean().sort_values(ascending=False).head(10)

CodigoCliente
14048190    5100.000000
12719444    3840.000000
12291643    3756.500000
11618884    3718.380952
12549492    3240.000000
12404538    3213.772727
12291291    3202.000000
12282136    3136.800000
13778771    3072.000000
13876309    3000.000000
Name: ordered_boxes, dtype: float64

In [ ]:
medellin = (6.251290,-75.5812)
bogota = (4.6100,-74.0833)

In [8]:
from haversine import haversine, Unit
medellin = (6.251290,-75.5812)
bogota = (4.6100,-74.0833)
# This one is correct, ours isn't
haversine(medellin, bogota, unit=Unit.KILOMETERS) # Medellin to Bogota

246.57451679533824

In [9]:
import requests

url = "https://router.project-osrm.org/route/v1/driving/-74.0833,4.6100;-75.5812,6.251290?overview=false" # driving makes it sure it's the car

response = requests.get(url)
data = response.json()

distance_km = data['routes'][0]['distance'] / 1000  # in km
duration_h = data['routes'][0]['duration'] / 3600   # in minutes

print(f"Distance: {distance_km:.2f} km")
print(f"Duration: {duration_h:.1f} h")

/Users/amelie/Library/CloudStorage/OneDrive-epfl.ch/04_Operations/project/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

Distance: 415.69 km
Duration: 6.4 h

In [10]:
def get_distance(frm, to):
    """Takes two points in the form of (lat, lon) and returns the distance and duration between them."""
    url = f"https://router.project-osrm.org/route/v1/driving/{frm[1]},{frm[0]};{to[1]},{to[0]}?overview=false"
    response = requests.get(url)
    data = response.json()
    distance_km = data['routes'][0]['distance'] / 1000  # in km
    duration_h = data['routes'][0]['duration'] / 3600   # in h
    return distance_km, duration_h

get_distance(bogota, medellin) # Medellin to Bogota

(415.686, 6.407722222222222)

In [25]:
import utils
utils.get_distance(bogota, medellin) # Medellin to Bogota

(415.686, 6.407722222222222)

In [11]:
test = df.head(10)

In [12]:
test['lat'] = [4.6100,6.251290] * 5
test['long'] = [-74.0833, -75.5812] * 5

/var/folders/t8/crqx384x59sbfjcs2flq1d380000gn/T/ipykernel_33162/312598344.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['lat'] = [4.6100,6.251290] * 5
/var/folders/t8/crqx384x59sbfjcs2flq1d380000gn/T/ipykernel_33162/312598344.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['long'] = [-74.0833, -75.5812] * 5

In [ ]:
coords = list(set(zip(test['lat'], test['long'])))
coord_labels = [f"{lat:.5f},{lon:.5f}" for lat, lon in coords]
coord_map = dict(zip(coord_labels, coords))  # map label to (lat, lon)

# Initialize empty matrices
distance_matrix = pd.DataFrame(index=coord_labels, columns=coord_labels)
time_matrix = pd.DataFrame(index=coord_labels, columns=coord_labels)

# Compute distances and times
for from_label, to_label in product(coord_labels, repeat=2):
    from_coord = coord_map[from_label]
    to_coord = coord_map[to_label]
    dist, duration = get_distance(from_coord, to_coord)
    distance_matrix.loc[from_label, to_label] = round(dist, 2)
    time_matrix.loc[from_label, to_label] = round(duration, 2)

In [16]:
distance_matrix

                  6.25129,-75.58120 4.61000,-74.08330
6.25129,-75.58120               0.0            405.73
4.61000,-74.08330            415.69               0.0

In [ ]:
# Trying